[package]
authors = ["Mathieu Rene <mathieu.rene@gmail.com>"]
edition = "2018"
name = "minidsp"
version = "0.0.1-pre2"
license = "MIT"
description = "A control interface for some MiniDSP products"
repository = "https://github.com/mrene/minidsp-rs"
keywords = ["minidsp","audio","dsp"]

[dependencies]
anyhow = "1.0.36"
async-stream = "0.3.0"
async-trait = "0.1.42"
bytes = "1.0.0"
clap = "3.0.0-beta.2"
env_logger = "0.8.2"
futures = "0.3.8"
futures-sink = "0.3.8"
futures-util = "0.3.8"
hex = "0.4.2"
log = "0.4.11"
thiserror = "1.0.22"
tokio-stream = "0.1.0"
hexplay = "0.2.1"
enum-utils = "0.1.2"
cec-rs = {version="2.2.0",optional=true}
libcec-sys = {version="1.0.7",optional=true}
arrayvec = "0.5.2"

[dependencies.hidapi]
optional = true
version = "1.2.5"
features = ["linux-static-libusb"]
default_features = false

[dependencies.tokio]
features = ["full"]
version = "1.0.1"

[dependencies.tokio-util]
features = ["full"]
version = "0.6.0"

[features]
default = ["hid", "cec"]
hid = ["hidapi"]
cec = ["cec-rs","libcec-sys"]

[target.arm-unknown-linux-gnueabihf]
linker="gcc-sysroot"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
